export const apiEndpoints = {
  auth: {
    LOGIN: '/auth/login',
    VERIFY_OTP: '/auth/otp/process',
    FORGOT_PASSWORD: '/auth/forgot-password',
    FORGOT_PASSWORD_OTP: '/auth/password/otp/process',
    RESET_PASSWORD: '/auth/reset-password',
    RESEND_OTP: '/auth/otp/resend',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    VERIFY_EMAIL: '/auth/verify',
  },
  user: {
    GET_BANK_DETAILS: '/merchant/settlements/accounts/default-account',
  },
  transaction: {
    GET_BALANCE: '/merchant/client/get-balance',
    GET_MERCHANT_BALANCE: '/merchant/dashboard/balance',
    GET_TRANSACTIONS: '/merchant/dashboard/transactions',
    GET_SETTLEMENT_ACCOUNTS: '/merchant/settlements/accounts',
    ADD_SETTLEMENT_ACCOUNT: '/merchant/settlements/accounts/store',
    GET_SETTLEMENT_HISTORY: '/merchant/settlements/history',
    POPULATE_SETTLEMENT_CHARTS: '/merchant/dashboard/settlement-chart',
    CHANGE_ACCOUNT_STATUS: '/merchant/settlements/accounts',
    GET_WALLET_HISTORY: '/merchant/client/get-wallet-logs',
    GET_WALLET_EXPORT_STATUS: '/merchant/client/wallet-exports/:id/status',

    EXPORT_WALLET_HISTORY_TRANSACTIONS: '/merchant/client/get-wallet-logs',
    GET_WALLET_HISTORY_EXPORT_STATUS: '/merchant/client/wallet-exports/:id/status',
 },
  collections: {
    GET_COLLECTION_HISTORY: '/merchant/collections-history',
    GET_PAYMENT_LINKS: '/merchant/payment-links',
    CREATE_PAYMENT_LINK: '/merchant/payment-links/store',
    UPDATE_PAYMENT_LINK: '/merchant/payment-links/update',
    GET_VIRTUAL_ACCOUNTS: '/merchant/virtual-accounts',
    REQUEST_VIRTUAL_ACCOUNT: '/merchant/virtual-accounts/store',
    REPUSH_NOTIFICATION: '/merchant/collections-history',
    GET_PAYMENT_MANDATES: '/merchant/mandates',
    CREATE_PAYMENT_MANDATE: '/merchant/mandates/store',
    REFRESH_STATUS: '/merchant/mandates',
    REQUEST_REFUND: '/merchant/refunds/initiate',
    GET_SINGLE_REFUNDS: '/merchant/refunds',
    GET_REFUNDS: '/merchant/refunds',
    GET_COLLECTION_GATEWAY_META: '/merchant/collections-history/:id/gateway-meta',
    EXPORT_COLLECTION_HISTORY_TRANSACTIONS: '/merchant/collections-history',
    GET_COLLECTION_EXPORT_STATUS: '/merchant/client/exports/:id/status',
  },
  conversions: {
    GET_CONVERSION_HISTORY: '/conversions/history',
    GET_CONVERSION_EXPORT: '/conversions/export',
    GET_COLLECTION_HISTORY: '/merchant/collections-history',
    GET_PAYMENT_LINKS: '/merchant/payment-links',
    CREATE_PAYMENT_LINK: '/merchant/payment-links/store',
    UPDATE_PAYMENT_LINK: '/merchant/payment-links/update',
    GET_VIRTUAL_ACCOUNTS: '/merchant/virtual-accounts',
    REQUEST_VIRTUAL_ACCOUNT: '/merchant/virtual-accounts/store',
    REPUSH_NOTIFICATION: '/merchant/collections-history',
    GET_PAYMENT_MANDATES: '/merchant/mandates',
    CREATE_PAYMENT_MANDATE: '/merchant/mandates/store',
    REFRESH_STATUS: '/merchant/mandates',
    REQUEST_REFUND: '/merchant/refunds/initiate',
    GET_SINGLE_REFUNDS: '/merchant/refunds',
    GET_REFUNDS: '/merchant/refunds',
  },
  bank: {
    GET_BANKS: '/utilities/banks',
    NAME_CHECK: '/utilities/verify-account',
  },
  subaccount: {
    GET_SUBACCOUNT_HISTORY: '/merchant/subaccounts',
    POST_SUBACCOUNT_AMOUNT: '/merchant/subaccounts/store',
    UPDATE_SUBACCOUNT_AMOUNT: '/merchant/subaccounts/',
    UPDATE_SUBACCOUNT_MODE: '/merchant/subaccounts/',
    DEACTIVATE_SUBACCOUNT: '/merchant/subaccounts/',
  },
  kyc: {
    GET_KYC_METHODS: '/merchant/kyc/methods',
    CREATE_KYC: '/merchant/kyc/requests/store',
    GET_KYC: '/merchant/kyc/request',
  },
  payouts: {
    GET_PAYOUT_HISTORY: '/merchant/disbursements',
    ADD_PAYOUT: '/merchant/disbursements/interbank',
    VERIFY_PAYOUT_OTP: '/merchant/disbursements/interbank/complete',
    REQUERY_PAYOUT: '/merchant/disbursements/interbank/requery',
    EXPORT_PAYOUT_HISTORY_TRANSACTIONS: '/merchant/disbursements',
    GET_PAYOUT_EXPORT_STATUS: '/merchant/client/exports/:id/status',
    REQUEST_REFUND: '/merchant/disbursements/refunds', // TODO: re-check
    RAISE_DISPUTE: '/merchant/disbursements/disputes', // TODO: re-check
  },
  webhooks: {
    GET_WEBHOOK: '/merchant/webhook',
    UPDATE_WEBHOOK: '/merchant/webhook/store',
  },
  settings: {
    GET_API_CREDENTIALS: '/api-credentials',
    GET_ROLES: '/merchant/roles',
    DELETE_ROLE: '/merchant/roles',
    GET_USERS: '/merchant/users',
    ADD_USER: '/merchant/users/store',
    UPDATE_USER: 'merchant/users/update',
    GET_PERMISSIONS: '/utilities/permissions',
    CHANGE_USER_STATUS: '/merchant/users/status',
    GET_ROLE_PERMISSIONS: '/merchant/roles',
    ADD_ROLE: '/merchant/roles/create',
    UPDATE_ROLE: '/merchant/roles/update',
    GENERATE_ACCESS_KEY: '/api-credentials/rotate-access-keys',
    GENERATE_ENCRYPTION_KEY: '/api-credentials/rotate-encryption-keys',
    UPDATE_PROFILE: '/merchant/profile/update',
    GET_USER_LOG: '/merchant/profile/logs',
  },
  mids: {
    GET_MIDS: '/merchant/mids',
  },
  categories: {
    GET_CATEGORIES: '/merchant/category',
  },
  utilities: {
    UPLOAD_FILE: '/utilities/upload',
    SUPPORTED_COUNTRIES: '/utility/supported-countries',
  },
  ecommerce: {
    GET_SHIPPING_SETTINGS: '/merchant/ecommerce/shippings',
    ADD_SHIPPING_FEE: '/merchant/ecommerce/shippings/store',
    GET_SHIPPING_ORDERS: '/merchant/ecommerce/orders',
  },
  ipWhitelist: {
    GET_IP_WHITELIST: '/merchant/ip-whitelist',
    CREATE_IP_WHITELIST: '/merchant/ip-whitelist',
    UPDATE_IP_WHITELIST: '/merchant/ip-whitelist',
    DELETE_IP_WHITELIST: '/merchant/ip-whitelist',
  },
  settlements: {
    LIST_SETTLEMENTS: '/merchant/settlements',
    GET_SETTLEMENT_DETAILS: '/merchant/settlements/:id',
    GET_DAILY_BREAKDOWN: '/merchant/settlements/daily-breakdown',
    GET_SETTLEMENT_WINDOW_TRANSACTIONS: '/merchant/settlements/:id/window-transactions',
    EXPORT_SETTLEMENT_WINDOW_TRANSACTIONS: '/merchant/settlements/:id/window-transactions',
    GET_SETTLEMENT_EXPORT_STATUS: '/merchant/settlements/export-jobs/:id/status',
  },
};
