export const apiEndpoints = {
  auth: {
    LOGIN: "/auth/login",
    VERIFY_OTP: "/auth/otp/process",
    FORGOT_PASSWORD: "/auth/forgot-password",
    FORGOT_PASSWORD_OTP: "/auth/password/otp/process",
    RESET_PASSWORD: "/auth/reset-password",
    RESEND_OTP: "/auth/otp/resend",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    VERIFY_EMAIL: "/auth/verify",
  },
  user: {
    GET_BANK_DETAILS: "/merchant/settlements/accounts/default-account",
  },
  transaction: {
    GET_BALANCE: "/merchant/dashboard/balance",
    GET_TRANSACTIONS: "/merchant/dashboard/transactions",
    GET_SETTLEMENT_ACCOUNTS: "/merchant/settlements/accounts",
    ADD_SETTLEMENT_ACCOUNT: "/merchant/settlements/accounts/store",
    GET_SETTLEMENT_HISTORY: "/merchant/settlements/history",
    POPULATE_SETTLEMENT_CHARTS: "/merchant/dashboard/settlement-chart",
    CHANGE_ACCOUNT_STATUS: "/merchant/settlements/accounts",
    GET_WALLET_HISTORY: "/merchant/wallet-history",
  },
  collections: {
    GET_COLLECTION_HISTORY: "/merchant/collections-history",
    GET_PAYMENT_LINKS: "/merchant/payment-links",
    CREATE_PAYMENT_LINK: "/merchant/payment-links/store",
    UPDATE_PAYMENT_LINK: "/merchant/payment-links/update",
    GET_VIRTUAL_ACCOUNTS: "/merchant/virtual-accounts",
    REQUEST_VIRTUAL_ACCOUNT: "/merchant/virtual-accounts/store",
    REPUSH_NOTIFICATION: "/merchant/collections-history",
    GET_PAYMENT_MANDATES: "/merchant/mandates",
    CREATE_PAYMENT_MANDATE: "/merchant/mandates/store",
    REFRESH_STATUS: "/merchant/mandates",
  },
  bank: {
    GET_BANKS: "/utilities/banks",
    NAME_CHECK: "/utilities/verify-account",
  },
  subaccount: {
    GET_SUBACCOUNT_HISTORY: "/merchant/subaccounts",
    POST_SUBACCOUNT_AMOUNT: "/merchant/subaccounts/store",
    UPDATE_SUBACCOUNT_AMOUNT: "/merchant/subaccounts/",
    UPDATE_SUBACCOUNT_MODE: "/merchant/subaccounts/",
    DEACTIVATE_SUBACCOUNT: "/merchant/subaccounts/",
  },
  kyc: {
    GET_KYC_METHODS: "/merchant/kyc/methods",
    CREATE_KYC: "/merchant/kyc/requests/store",
    GET_KYC: "/merchant/kyc/request",
  },
  disbursements: {
    GET_DISBURSEMENT_HISTORY: "/merchant/disbursements",
    ADD_DISBURSEMENT: "/merchant/disbursements/interbank",
    VERIFY_DISBURSEMENT_OTP: "/merchant/disbursements/interbank/complete",
  },
  webhooks: {
    GET_WEBHOOK: "/merchant/webhook",
    UPDATE_WEBHOOK: "/merchant/webhook/store",
  },
  settings: {
    GET_API_CREDENTIALS: "/api-credentials",
    GET_ROLES: "/merchant/roles",
    DELETE_ROLE: "/merchant/roles",
    GET_USERS: "/merchant/users",
    ADD_USER: "/merchant/users/store",
    UPDATE_USER: "merchant/users/update",
    GET_PERMISSIONS: "/utilities/permissions",
    CHANGE_USER_STATUS: "/merchant/users/status",
    GET_ROLE_PERMISSIONS: "/merchant/roles",
    ADD_ROLE: "/merchant/roles/create",
    UPDATE_ROLE: "/merchant/roles/update",
    GENERATE_ACCESS_KEY: "/api-credentials/rotate-access-keys",
    GENERATE_ENCRYPTION_KEY: "/api-credentials/rotate-encryption-keys",
    UPDATE_PROFILE: "/merchant/profile/update",
    GET_USER_LOG: "/merchant/profile/logs",
  },
  mids: {
    GET_MIDS: "/merchant/mids",
  },
  utilities: {
    UPLOAD_FILE: "/utilities/upload",
  },
  ecommerce: {
    GET_SHIPPING_SETTINGS: "/merchant/ecommerce/shippings",
    ADD_SHIPPING_FEE: "/merchant/ecommerce/shippings/store",
    GET_SHIPPING_ORDERS: "/merchant/ecommerce/orders",
  },
};
